def shelp():
    print("\n\n")
    print("HOW TO PLAY\n")
    print("When you first start the game, you will be met with an ASCII image of a room and an input prompt.")
    print("In this prompt, you can type 'quit' to quit or any of the letters shown in the map. Here is what each letter/symbol means:")
    print("\nACTION LETTERS (doors, chests, etc.)\n")
    print("C - Chest")
    print("D - Door")
    print("I - Info hologram")
    print("\nDESIGN SYMBOLS (wall, player, etc.)\n")
    print("# - Wall")
    print("@ - The Player")
    print("\nOTHER COMMANDS\n")
    print("inv or inventory - View your inventory")
    print("help - shows this help")
    print("redraw - redraw the room")